### ISSUE TITLE
Authentication example (with cookies)?

### ISSUE THREAD

**Issue by Jarred-Sumner** [timetocode/nengi#16]
Before connecting to the game, players authenticate via `passport.js` outside the scope of Nengi.

To support that, I currently use this hack:
```typescript
const wsServer = this.instance.wsServer;
wsServer.on("connection", (ws, req) => {
  var client = this.instance.connect(ws);

  client.onLoadSession = new Promise((resolve, reject) => {
    wsUse(session, req).then(() => {
      client.session = req.session;
      resolve();
    });
  });

  ws.on("message", (message) => {
    this.instance.onMessage(message, client);
  });

  ws.on("close", (event) => {
    this.instance.disconnect(client, event);
  });
});
```

This overrides what `nengi.Instance` does but adds this `onLoadSession` callback to run `express-session` and read their session cookie from the HTTP request

When the user is not authenticated, it disconnects them:
```typescript
if (isGuest) {
  console.log("[GameInstance]", "Disconnecting guest");
  this.instance.disconnect(client, null);
  return;
}
```

Is there a better way of doing this? I'd prefer to use cookies instead of a JWT so that the client doesn't have to do anything special to auth requests

**Comment by timetocode** [comment]
The nengi.Instance can be passed an http server via `new nengi.Instance(nengiConfig, { httpServer })` where `httpServer` is https://nodejs.org/api/http.html. This allows for configuration of the base http server object which I think is the same thing express uses under the hood. My guess is it could be shared with express via `httpServer.createServer(expresssApp)` though I have not tried it. If you end up needing to attach some data to an object that is created by the `httpServer` and eventually finds its way to the nengi connect handler, it is worth noting that the serverside `client.connection` in nengi is the socket object created by cws which is the websocket library that handles the http upgrade request ( https://github.com/ClusterWS/cWS ). If you run into any trouble getting your desired data across these things (http -> nengi or http -> cws -> nengi) let me know and we can add something to help support this.

An alternative which is what I've been doing is to have an express app that hosts the webpage or web apis used by a game and adding an authentication api that can be called from nengi instances. The authentication service can be a regular express + express-session setup, with the added feature that it creates temporary tokens that identify players to the game instances. This api can generate random tokens (like uuidv4s or node crypto.randomBytes) and associate them with a user (authenticated or otherwise), e.g.  `11bf5b37 -> userId 1234` and then this token can be given to the nengi game client. When the client connects to the server, it passes the token like this:
```js
client.connect(websocketAddress, { token: '11bf5b37' })
```
and then the server can identify them
```js
instance.on('connect', ({ client, data, callback }) => {
  /* ... */
  if (data.fromClient.token) {
     //pseudocode:
     playerAPI.request({ token: data.fromClient.token })
       .then(user => {
          // user object returned by backend
          // use some this persisted data in the game.. e.g set their username
          // or store their playerId so we can make api requests to save their character periodically
       })
       .catch(/*etc*/)
  }
  /* ... */
})
```

**Comment by Jarred-Sumner** [comment]
That would work – I currently pass nengi a custom HTTP server and use Express like your example.

I'm using cookies right now to minimize the number of HTTP requests back & forth until the user can start playing – I want the game to load really fast.

Its also a little easier to just let the browser deal with sessions after they've already logged in once, rather than having code that checks & persists auth tokens

But I'm probably over-optimizing/being overly pedantic
