### ISSUE TITLE
Features about scalable and room?

### ISSUE THREAD

**Issue by GDdark** [timetocode/nengi#3]
It's a great project!  
I have a few questions. 
can i make multiple processes by using nengi?  
Is the project offer some features such as room making so that I can separate users into different rooms?

**Comment by timetocode** [comment]
Thank you. 

And yes, the `nengi.Instance` is the server-side of the game, and one can create multiple processes where each process runs an instance. There are several ways to use this to scale a game. The most common way is just to run the server side of the game multiple times, on different ports and/or different machines.

For a few games now I've used something like a $5 vultr vps for servers. Depending on the game I can generally get ~40-120 concurrent users on that type of server. If the game has small rooms then I open multiple instances per server. If the game is one single large room then I open one instance per server. Either way, I then add as many total servers as is needed to handle the total peak player population. I've gone up to a couple thousand players worth of capacity this way.

**Comment by GDdark** [comment]
Thank you again.

I understood. But I think it's inconvenient that I have to make more instances (another process using different port or different server) to separate users. It's also difficult to make some room-matchings conditionally. 

hmmmm!

**Comment by timetocode** [comment]
One can also make multiple instances within a single process, which is how https://jigsawpuzzles.io/ works. It can open 20-40 instances per server.  Is that more like what you had in mind?

In fact that game maintains a pool of "idle" instances (like rooms) which are waiting for players to start a new puzzle or continue a saved puzzle. When a player arrives on a url that corresponds to a puzzle, the front end will connect them to a game in progress if that puzzle is currently being played, or it will tell the back end to load that puzzle into one of the idle instances. In fact from the player's perspective they're not even aware that their puzzles have ever been saved to a database and unloaded from an instance -- any time they try to play it is as if their puzzle room is always running. I mention this to demonstrate an advanced case of matching players to a room.

From the outside JigsawPuzzles.io would still work very similarly by opening 20-40 separate processes. In fact the only reason I did not open that many processes is that I was trying to squeeze many tiny instances onto one  weak server with 500 MB of RAM and doing this avoided the 20 MB overhead from running each instance as a separate node process. If that server had more RAM I would go back to making the instances separate processes  so that I could turn them on/off one at a time instead of all together (this also applies if one of them crashes).  I do not particularly recommend this approach unless someone has tiny rooms and no other choice but to optimize for memory.

**Comment by timetocode** [comment]
I had another thought.. which is in the future there is another api being added called `nengi.Channel.` In it the game code creates channels, and then adds clients (players) to the channel. The players then see whatever happens in that channel. All of this occurs within a single instance. Would this be a close fit for your idea of a room?

I'm always looking to make things easier to use, so if you have any example features that don't work well with nengi let me know and I can start to think about how to approach them.

**Comment by GDdark** [comment]
Yes. That's what I mean. Thank you for taking my opinion

**Comment by timetocode** [comment]
Whoops I should have closed this ages ago. 

There's a provision channel api implemented now that offers this room-style functionality. It is at an 'experimental' stability level, but looks like it is going to fit the bill. [https://timetocode.com/nengi/man/channel](https://timetocode.com/nengi/man/channel)

Thanks again for the comment
